### ISSUE TITLE
Blob is not defined at configureWebWorker

### ISSUE THREAD

**Issue by sujeongkim** [CesiumGS/3d-tiles-validator#215]
I am trying to use the validator to convert gltf/glb into a tileset, but I get an error saying "Blob is not defined at configureWebWorker".
Running` npm run test` also produces the same error (copied and pasted below).

```
> 3d-tiles-validator@0.1.0 test
> gulp test

ReferenceError: Blob is not defined
    at configureWebWorker (/home/e29095/projects/3d-tiles-validator/validator/node_modules/cesium/Build/CesiumUnminified/Cesium.js:244354:49710)
    at /home/e29095/projects/3d-tiles-validator/validator/node_modules/cesium/Build/CesiumUnminified/Cesium.js:247891:3
    at /home/e29095/projects/3d-tiles-validator/validator/node_modules/cesium/Build/CesiumUnminified/Cesium.js:25:66
    at Object.<anonymous> (/home/e29095/projects/3d-tiles-validator/validator/node_modules/cesium/Build/CesiumUnminified/Cesium.js:28:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by lilleyse** [comment]
Hi @sujeongkim, this bug is similar to https://github.com/CesiumGS/obj2gltf/issues/269 and we're hoping to fix it soon.

You can work around this bug in the meantime by using Node 14 or by editing package.json so that the cesium version is `1.84.0` (no caret symbol)

**Comment by lilleyse** [comment]
CesiumJS 1.86.1 was released with a fix so 3d-tiles-validator should be fixed as well, just make sure to reinstall packages with `npm install -f`
